worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream order_api { server order-service-webapi:8080; }
    upstream catalog_api { server catalog-api:8080; }
    # upstream discount_api { server discount-service:8080; }
    upstream chat_api { server chat-api:8080; }
    upstream auth_api { server auth-service:8080; }

    server {
        listen 80;

        # Order Service
        location /api/order/ {
            proxy_pass http://order_api;
            proxy_set_header Host $host;
        }

        # Catalog Service
        location /api/catalog/ {
            proxy_pass http://catalog_api/api/;
            proxy_set_header Host $host;
        }

        # Discount Service
        # location /api/discount/ {
        #     proxy_pass http://discount_api;
        #     proxy_set_header Host $host;
        # }

        # Chat Service
        location /api/chat/ {
            proxy_pass http://chat_api;
            proxy_set_header Host $host;
        }

        # Auth Service
        location /api/v1/auth/ {
            proxy_pass http://auth_api;
            proxy_set_header Host $host;
        }
    }
}