name: delivery-hub-cluster

services:

  # ---------------- ORDER SERVICE ----------------
  order-service-webapi:
    build:
      context: ../../
      dockerfile: Services/OrderService/Dockerfile
    container_name: order-service-webapi
    ports:
      - "7225:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      JWTSettings__jwksUrl: http://auth-service:8080/.well-known/jwks.json
      RabbitMQ__Hostname: rabbitmq
      # ConnectionStrings__OrderDatabase: "Host=order-postgres;Port=5432;Database=OrderDb;Username=postgres;Password=postgres"
      ConnectionStrings__OrderDatabase: "Host=general-postgres;Port=5432;Database=OrderDb;Username=postgres;Password=postgres"
    depends_on:
      - rabbitmq
      # - order-postgres
      - general-postgres
    networks:
      - backend
      - rabbitmq

  # order-postgres:
  #   image: postgres:16-alpine
  #   container_name: order-postgres
  #   environment:
  #     POSTGRES_DB: OrderDb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - order_postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - backend


  # ---------------- CATALOG SERVICE ----------------
  catalog-api:
    build:
      context: ../../
      dockerfile: Services/CatalogService/Catalog.API/Dockerfile
    container_name: catalog-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Mongo__Database=${MONGO_INITDB_DATABASE}
      - Mongo__ConnectionString=${MONGO_ConnectionString}
    depends_on:
      - mongo
    volumes:
      - ../../Services/CatalogService/Catalog.API/Assets/product-images:/app/wwwroot/images
    networks:
      - backend

  mongo:
    image: mongo:7.0
    container_name: dh-catalog-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
      - ./init/mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - backend


  # ---------------- DISCOUNT SERVICE ----------------
  discount-service:
    build:
      context: ../../Services/DiscountService
      dockerfile: DiscountService.Api/Dockerfile
      args:
        MOD: Debug
    container_name: discount-service
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # ConnectionStrings__DiscountDb: "Host=discount-postgres;Port=5432;Database=DiscountDb;Username=postgres;Password=postgres"
      ConnectionStrings__DiscountDb: "Host=general-postgres;Port=5432;Database=DiscountDb;Username=postgres;Password=postgres"
    depends_on:
      # - discount-postgres
      - general-postgres
    networks:
      - backend

  # discount-postgres:
  #   image: postgres:15-alpine
  #   container_name: discount-postgres
  #   environment:
  #     POSTGRES_DB: DiscountDb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - discount_postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - backend


  # ---------------- CHAT SERVICE ----------------
  chat-api:
    build:
      context: ../../Services/ChatService
      dockerfile: Dockerfile
    container_name: chat-api
    ports:
      - "7190:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # ConnectionStrings__DefaultConnection: "Host=chat-postgres;Port=5432;Database=DeliveryHubChatDb;Username=postgres;Password=postgres"
      ConnectionStrings__Postgres: "Host=general-postgres;Port=5432;Database=DeliveryHubChatDb;Username=postgres;Password=postgres"
      ConnectionStrings__Redis: "redis:6379,abortConnect=false"
      ServicesConfig__CatalogApi__BaseUrl: "http://catalog-api:8080"
      JWTSettings__jwksUrl: "http://auth-service:8080/.well-known/jwks.json"
    depends_on:
      redis:
        condition: service_healthy
      general-postgres:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped
    
  # chat-postgres:
  #   image: postgres:16
  #   container_name: chat-postgres
  #   environment:
  #     POSTGRES_DB: DeliveryHubChatDb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5435:5432"
  #   volumes:
  #     - chat_postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - backend
  #   restart: unless-stopped


  # ---------------- AUTH SERVICE ----------------
  auth-service:
    build:
      context: ../../Services/AuthService
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "7119:8080"
      - "7120:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      APPLY_MIGRATIONS: "true"
      # ConnectionStrings__Postgres: "Host=auth-postgres;Port=5432;Database=auth_db;Username=postgres;Password=postgres"
      ConnectionStrings__Postgres: "Host=general-postgres;Port=5432;Database=auth_db;Username=postgres;Password=postgres;GssEncryptionMode=Disable"
      Jwt__Issuer: "AuthService"
      Jwt__AccessTokenMinutes: "15"
      Jwt__RefreshTokenDays: "30"
      Jwt__KeyId: "auth-key-001"
      Jwt__PrivateKeyPath: "/run/secrets/jwt_private.pem"
      Jwt__PublicKeyPath: "/run/secrets/jwt_public.pem"
      ServiceClients__0__ClientId: order-service
      ServiceClients__0__ClientSecret: order-service-secret-dev
      ServiceClients__0__AllowedScopes: service order.read order.write catalog.read catalog.write discount.read discount.write chat.read chat.write feedback.read feedback.write profile.read profile.write auth.read auth.write

      ServiceClients__1__ClientId: catalog-service
      ServiceClients__1__ClientSecret: catalog-service-secret-dev
      ServiceClients__1__AllowedScopes: service order.read order.write catalog.read catalog.write discount.read discount.write chat.read chat.write feedback.read feedback.write profile.read profile.write auth.read auth.write

      ServiceClients__2__ClientId: discount-service
      ServiceClients__2__ClientSecret: discount-service-secret-dev
      ServiceClients__2__AllowedScopes: service order.read order.write catalog.read catalog.write discount.read discount.write chat.read chat.write feedback.read feedback.write profile.read profile.write auth.read auth.write

      ServiceClients__3__ClientId: chat-service
      ServiceClients__3__ClientSecret: chat-service-secret-dev
      ServiceClients__3__AllowedScopes: service order.read order.write catalog.read catalog.write discount.read discount.write chat.read chat.write feedback.read feedback.write profile.read profile.write auth.read auth.write

      ServiceClients__4__ClientId: feedback-service
      ServiceClients__4__ClientSecret: feedback-service-secret-dev
      ServiceClients__4__AllowedScopes: service order.read order.write catalog.read catalog.write discount.read discount.write chat.read chat.write feedback.read feedback.write profile.read profile.write auth.read auth.write

      ServiceClients__5__ClientId: profile-service
      ServiceClients__5__ClientSecret: profile-service-secret-dev
      ServiceClients__5__AllowedScopes: service order.read order.write catalog.read catalog.write discount.read discount.write chat.read chat.write feedback.read feedback.write profile.read profile.write auth.read auth.write

      ServiceClients__6__ClientId: auth-service
      ServiceClients__6__ClientSecret: auth-service-secret-dev
      ServiceClients__6__AllowedScopes: service order.read order.write catalog.read catalog.write discount.read discount.write chat.read chat.write feedback.read feedback.write profile.read profile.write auth.read auth.write
    depends_on:
      - general-postgres
      # auth-postgres:
      #   condition: service_healthy
    networks:
      - backend
    volumes:
      - dp_keys:/var/dpkeys
      - ../../Services/AuthService/src/Auth.Api/Secrets/jwt_private.pem:/run/secrets/jwt_private.pem:ro
      - ../../Services/AuthService/src/Auth.Api/Secrets/jwt_public.pem:/run/secrets/jwt_public.pem:ro

  # auth-postgres:
  #   image: postgres:16-alpine
  #   container_name: auth-postgres
  #   environment:
  #     POSTGRES_DB: auth_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5436:5432"
  #   volumes:
  #     - auth_postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20
  #   networks:
  #     - backend

  # ---------------- RABBITMQ ----------------
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ../Rabbit
      dockerfile: Dockerfile
    volumes:
      - /var/lib/rabbitmq
      - /var/log/rabbitmq
      - ../Rabbit/definitions.json:/etc/rabbitmq/definitions.json
      - ../Rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq

  # ---------------- NGINX ----------------
  gateway:
    build:
      context: nginx
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - order-service-webapi
      - catalog-api
      - discount-service
      - chat-api
    networks:
      - backend
  
  general-postgres:
    image: postgres:16-alpine
    container_name: general-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - general_postgres_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d OrderDb"]
      interval: 5s
      timeout: 5s
      retries: 20
      
  redis:
    image: redis:7-alpine
    container_name: general-redis
    ports:
      - "6380:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  backend:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  # order_postgres_data:
  # discount_postgres_data:
  # chat_postgres_data:
  # auth_postgres_data:
  general_postgres_data:
  mongo_data:
  dp_keys: