using Catalog.Application.Repositories;
using Catalog.Application.Services;
using Catalog.Infrastructure.Helpers;
using Catalog.Infrastructure.Mongo;
using Catalog.Infrastructure.Repositories;
using Catalog.Infrastructure.Seed;
using Catalog.Infrastructure.Services;
using DeliveryHub.Catalog.Application.Services;
using DeliveryHub.Catalog.Domain.Appliaction.Repositories;
using DeliveryHub.Catalog.Infrastructure.Repositories;
using DeliveryHub.Catalog.Infrastructure.Services;
using MongoDB.Driver;
using Shared.Web.Middlewares;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

var services = builder.Services;

services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
services.AddEndpointsApiExplorer();

// configure Swashbuckle to include XML comments
services.AddSwaggerGen(options =>
{
    // automatically find the XML file generated by the compiler
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath))
    {
        options.IncludeXmlComments(xmlPath);
    }

    // optional: allow using [SwaggerOperation], [SwaggerResponse] attributes
    //options.EnableAnnotations();
});

var connectionName = builder.Configuration["Mongo:ConnectionString"];
var dbName = builder.Configuration["Mongo:Database"];

services
    .AddMongoClient(connectionName, dbName)

    //Repos
    .AddScoped<ICategoryRepository, CategoryRepository>()
    .AddScoped<IProductRepository, ProductRepository>()
    .AddScoped<IStockRepository, StockRepository>()
    .AddScoped<IProductImageRepository, ProductImageRepository>()

    //Services
    .AddScoped<IProductSearchService, MongoProductSearchService>()
    .AddScoped<IProductService, ProductService>()
    .AddScoped<IImageService, ImageService>();

MongoMappings.Register();

services.AddTransient<MongoDatabase>(sp =>
{
    var database = sp.GetRequiredService<IMongoDatabase>();
    return new MongoDatabase(database);
});

services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyHeader();
        policy.AllowAnyMethod();
        policy.AllowAnyOrigin();
    });
});

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var mongoDb = scope.ServiceProvider.GetRequiredService<MongoDatabase>();
    await mongoDb.CreateIndexesAsync();
}

app.UseCors("AllowAll");

app.UseMiddleware<ExceptionHandlingMiddleware>();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();

    await CatalogDataSeeder.SeedAsync(app.Services);
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseAuthorization();

app.MapControllers();

app.Run();
