using Catalog.API.Seed;
using Catalog.Application.Repositories;
using Catalog.Application.Services;
using Catalog.Infrastructure.Helpers;
using Catalog.Infrastructure.Mongo;
using Catalog.Infrastructure.Repositories;
using Catalog.Infrastructure.Services;
using DeliveryHub.Catalog.Application.Services;
using DeliveryHub.Catalog.Domain.Appliaction.Repositories;
using DeliveryHub.Catalog.Infrastructure.Repositories;
using DeliveryHub.Catalog.Infrastructure.Services;
using Shared.Web.Middlewares;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();

// configure Swashbuckle to include XML comments
builder.Services.AddSwaggerGen(options =>
{
    // automatically find the XML file generated by the compiler
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath))
    {
        options.IncludeXmlComments(xmlPath);
    }

    // optional: allow using [SwaggerOperation], [SwaggerResponse] attributes
    //options.EnableAnnotations();
});

var connectionName = builder.Configuration["Mongo:ConnectionString"];
var dbName = builder.Configuration["Mongo:Database"];

builder.Services
    .AddMongoClient(connectionName, dbName)
    //.AddMongoRepository<Product>("products")
    //.AddMongoRepository<Category>("category")

    //Repos
    .AddScoped<ICategoryRepository, CategoryRepository>()
    .AddScoped<IProductRepository, ProductRepository>()
    .AddScoped<IStockRepository, StockRepository>()
    .AddScoped<IProductImageRepository, ProductImageRepository>()

    //Services
    .AddScoped<IProductSearchService, MongoProductSearchService>()
    .AddScoped<IProductService, ProductService>();

MongoMappings.Register();

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyHeader();
        policy.AllowAnyMethod();
        policy.AllowAnyOrigin();
    });
});

var app = builder.Build();

app.UseCors("AllowAll");

app.UseMiddleware<ExceptionHandlingMiddleware>();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();

    await CatalogDataSeeder.SeedAsync(app.Services);
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseAuthorization();

app.MapControllers();

app.Run();
