BEGIN;

-- USERS: добавила новые колонки Identity
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS user_name               varchar(320),
  ADD COLUMN IF NOT EXISTS normalized_user_name    varchar(320),
  ADD COLUMN IF NOT EXISTS normalized_email        varchar(320),

  ADD COLUMN IF NOT EXISTS email_confirmed         boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS phone_number_confirmed  boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS two_factor_enabled      boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS lockout_enabled         boolean NOT NULL DEFAULT true,

  ADD COLUMN IF NOT EXISTS security_stamp          text,
  ADD COLUMN IF NOT EXISTS concurrency_stamp       text;

-- USERS: заполнение полей для существующих пользователей
UPDATE users
SET
  user_name            = COALESCE(user_name, email),
  normalized_user_name = COALESCE(normalized_user_name, UPPER(COALESCE(user_name, email))),
  normalized_email     = COALESCE(normalized_email, UPPER(email)),
  security_stamp       = COALESCE(security_stamp, gen_random_uuid()::text),
  concurrency_stamp    = COALESCE(concurrency_stamp, gen_random_uuid()::text)
WHERE
  user_name IS NULL
  OR normalized_user_name IS NULL
  OR normalized_email IS NULL
  OR security_stamp IS NULL
  OR concurrency_stamp IS NULL;

-- USERS: сделала поля обязательными + добавила индексы
ALTER TABLE users
  ALTER COLUMN user_name SET NOT NULL,
  ALTER COLUMN normalized_user_name SET NOT NULL,
  ALTER COLUMN normalized_email SET NOT NULL,
  ALTER COLUMN security_stamp SET NOT NULL,
  ALTER COLUMN concurrency_stamp SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_normalized_user_name"
  ON users (normalized_user_name);

CREATE INDEX IF NOT EXISTS "IX_users_normalized_email"
  ON users (normalized_email);

-- ROLES: добавила новые колонки Identity
ALTER TABLE roles
  ADD COLUMN IF NOT EXISTS normalized_name   varchar(100),
  ADD COLUMN IF NOT EXISTS concurrency_stamp text;

UPDATE roles
SET
  normalized_name   = COALESCE(normalized_name, UPPER(name)),
  concurrency_stamp = COALESCE(concurrency_stamp, gen_random_uuid()::text)
WHERE normalized_name IS NULL OR concurrency_stamp IS NULL;

ALTER TABLE roles
  ALTER COLUMN normalized_name SET NOT NULL,
  ALTER COLUMN concurrency_stamp SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_roles_normalized_name"
  ON roles (normalized_name);

-- Identity нужны служебные таблицы
CREATE TABLE IF NOT EXISTS user_claims
(
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL,
  claim_type  text NULL,
  claim_value text NULL,
  CONSTRAINT "FK_user_claims_users_user_id"
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_user_claims_user_id"
  ON user_claims(user_id);

CREATE TABLE IF NOT EXISTS role_claims
(
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id     uuid NOT NULL,
  claim_type  text NULL,
  claim_value text NULL,
  CONSTRAINT "FK_role_claims_roles_role_id"
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_role_claims_role_id"
  ON role_claims(role_id);

CREATE TABLE IF NOT EXISTS user_logins
(
  login_provider        varchar(128) NOT NULL,
  provider_key          varchar(128) NOT NULL,
  provider_display_name text NULL,
  user_id               uuid NOT NULL,
  CONSTRAINT "PK_user_logins" PRIMARY KEY (login_provider, provider_key),
  CONSTRAINT "FK_user_logins_users_user_id"
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_user_logins_user_id"
  ON user_logins(user_id);

CREATE TABLE IF NOT EXISTS user_tokens
(
  user_id        uuid NOT NULL,
  login_provider varchar(128) NOT NULL,
  name           varchar(128) NOT NULL,
  value          text NULL,
  CONSTRAINT "PK_user_tokens" PRIMARY KEY (user_id, login_provider, name),
  CONSTRAINT "FK_user_tokens_users_user_id"
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

COMMIT;